### ISSUE TITLE
[C#/Windows] Consistent AtomicNET.dll referencing regardless of Editor build

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#1142]
Currently, an editor built from source on Windows (CMake_VS2015.bat, followed by building Atomic.sln), when generating an AtomicNET solution for a C# project will:
-Generate AtomicNET.* source projects into the project
-Generate AtomicProject.* projects, including AtomicProject.Desktop which has a dependency on AtomicNET.Desktop and will output artifacts to a /Debug directory, including the AtomicNET.dll generated by AtomicNET.Desktop
-Generate a solution with both projects

A distributable editor built with Build_AtomicEditor.bat on the other hand will:
-Generate AtomicProject.* projects, including AtomicProject,Desktop, with a dependency on a precompiled AtomicNET.dll in the editor install location, using an absolute path and will output artifacts to a /Release directory, including the referenced AtomicNET.dll
-Generate a solution with just these projects

This inconsistency makes moving between editor builds problematic, and also makes it impossible to have external projects that reliably reference the same AtomicNET.dll as AtomicProject.*, complicating commandline build processes.

To solve this I'd like to suggest the following:
For an editor build from source:
-Still generate AtomicNET.* source projects into the project, but have them output to a consistent location such as AtomicNET/Lib, regardless of build configuration (Debug/Release)
-Have generated AtomicProject.Desktop project reference the dll in AtomicNET/Lib, instead of directly referencing the project, but set AtomicNET.Desktop as a build dependency
-Still generate a solution with all projects

For a distributable editor:
-When generating AtomicNET projects, copy AtomicNET.dll to AtomicNET/Lib within the project
-Have generated AtomicProject.Desktop project reference the dll in AtomicNET/Lib, instead of directly referencing the the dll in the editor install location
-Still generate a solution with just AtomicProject.* projects

**Comment by JoshEngebretson** [comment]
Good progress on this in https://github.com/AtomicGameEngine/AtomicGameEngine/tree/JME-ATOMIC-1142

There are no longer any absolute paths in the portable and desktop projects, for example:

```xml
<OutputPath>../../Debug/Bin/Portable</OutputPath>
```

```xml
<None Include="../../Lib/Native/Windows/AtomicNETNative.dll">
   <Link>AtomicNETNative.dll</Link>
   <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</None>
```

It is possible to specify different assemblies based on config, here is a way of doing that for future reference... though, I don't think you can do this in the VS IDE?  Anyway, both debug/release point to AtomicProject/AtomicNET/Lib, though we can setup different ones if we want to... 

```xml
<Reference Include="AtomicNET">
   <HintPath Condition="'$(Configuration)' == 'Release'">../../Lib/Portable/AtomicNET.dll</HintPath>
   <HintPath Condition="'$(Configuration)' == 'Debug'">../../Lib/Portable/AtomicNET.dll</HintPath>
</Reference>
```

The assembly copy to the project happens anytime you generate the solution, or do a build, so shouldn't be sync issues with both Debug/Release going to Lib,  and I check modified times to save the copy if possible, so should be fast...

Removing absolute paths from the generated csproj's is a major win and we can still factor in Release/Debug subfolders on Lib if turns out we want/need to and as noted above we can use the HintPath to set this up.

I have a bunch of testing needed on this between the desktop/mobile platforms and Visual Studio/Xamarin Studio with both Debug/Release managed/native builds.  I should be able to land it tomorrow.  I plan on updating the External Project test too to make sure that running from a development build with AtomicNET included vs the binary build both work and are consistent...  I will also test command line builds with AtomicTool

Thankfully, root changes like this don't need to happen often and this is for the better, good call :)

**Comment by JoshEngebretson** [comment]
One other note, there are no project references now and all project assembly references are binary + project dependency instead

**Comment by mattbenic** [comment]
That's great, I'm really looking forward to this one :)

**Comment by JoshEngebretson** [comment]
Ok, https://github.com/AtomicGameEngine/AtomicGameEngine/pull/1163 should cover this, there are some details in the PR, the only thing I noticed detrimental is source navigation used to work with project references and now due to binary references, navigating to a method for example brings you to the binary assembly browser.  However, setting breakpoints and tracing still works, including on Android, sooooo still a NET positive, get it "NET" positive ;)

This change took a fair amount of testing, please let me know if any pins got bent or if the external project has some issues (or things could be better for the project)

**Comment by JoshEngebretson** [comment]
Oh, one other note, all it took to update the external project test: https://github.com/AtomicGameEngine/AtomicTests/commit/be66c29bc50accd488af93b1e7af4cc7d539b679 👍
