### ISSUE TITLE
[TypeScript] Generate native event constants and interface exports

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#1203]
We now have these in C#, will be pretty easy adding to TS decl

for example:

https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Script/AtomicEditor/editor/EditorEvents.ts#L149

**Comment by shaddockh** [comment]
I believe there is still an issue with being able to do this for TypeScript.  It is possible to generate a const enum in a ```d.ts``` file and the transpiler will automatically replace enums references with the constant value, but string enums are not supported. 
```
// Good
export enum MyEnum {
   opt1 = 1,
   opt2 = 2
}

// Bad
export enum MyEnum2 {
   opt1 = "opt1",
   opt2 = "opt2"
}
```
 Also, trying to define a constant value in a ```d.ts``` will cause an error.

```
// Bad
export const foo = "MyFoo";
```


The closest that can be done would be to maybe define a string ```type``` in the ```d.ts``` file so that the typechecker can catch any errors.  You would need to define an in-engine constant as well as a type.  It would looks something like this:

**d.ts**
```
export const EventType1 : "EventType1";  // This value would be populated from the C++ side like the other constants
export type EditorEventType = "EventType1" | "EventType2" | "EventType3"; // Define valid values for the EditorEventType
export function CallEvent(ev:EditorEventType);
```

**user code**
```
CallEvent("EventType1"); // This will pass the type checker
CallEvent("NewEvent"); // The type checker will identify this as an error

// or use the constant
CallEvent(EventType1);
```

Another option would be to generate a ```.ts``` file that contains all the constants and interfaces.  The only downside to this would be that it would not be an ambient declaration file and would need to be pulled in by an ```import``` clause for each file that needs it.

**Comment by shaddockh** [comment]
You mentioned that this is already working for C#; what would be an example ```.cs``` file that could be looked at to determine what should be generated for ```.ts```?

**Comment by shaddockh** [comment]
Ok, it's as I thought.  This won't work exactly like how the C# version works due to the fact that TypeScript types are only viable during the editing/transpiling phase.  That information does not get persisted into the emitted JavaScript so I don't believe there is going to be a way to get away from passing the event type.  I can however make the ```subscribeToEvent``` call more strictly typed though which is how I'm going to approach it.

Also, if there is a way to emit the ```uint``` values from the StringHash event names into the d.ts, then that could be a way around having to pass string literals...researching.

**Comment by JoshEngebretson** [comment]
Cool, this is looking great, with the exception of ```Atomic.NativeEventType.WidgetEvent```, it would be good to figure out some way to lookup the event hash id from Atomic.UIWidgetEvent, otherwise this is a major type safety loss (and having to specify a matching constant verbose/confusing).  

This would be a major win so really want to dig into it.  The solution has to be something that survives in the generated JS (seems obvious to state, though I find myself thinking about reflection on this, could be where we have to plug some duktape magic in).   Do you have any thoughts on somehow mapping the event hash id from the type provided in the generic method?  This could be grasping at straws :)

Also, are the event properties strongly typed here? for example ```e.target```

```typescript
window.subscribeToEvent<Atomic.UIWidgetEvent>(Atomic.NativeEventType.WidgetEvent, e=> {
       if (e.type == Atomic.UI_EVENT_TYPE_CLICK) {
           var target = e.target;
           if (target != null) {
               window.text = `Hello: ${target.id}`;
           }
       } 
    });
```

**Comment by shaddockh** [comment]
First the easy question .. yes, the ```e => ...``` is strongly typed in this example.

Now, the hard question about trying to look up the event id.  

I've been trying to figure out how to do this and I'm kind of at a loss.  You have to look past the syntax in the TypeScript because that is wiped out once it converts to JavaScript.  So, starting from there, the above function would look like this:
```javascript
window.subscribeToEvent(2070283606 /* WidgetEvent */ , e=> {
       if (e.type == Atomic.UI_EVENT_TYPE_CLICK) {
           var target = e.target;
           if (target != null) {
               window.text = "Hello: " + target.id;
           }
       } 
    });
```

The problem here is that there is nothing to reflect.  The ```subscribeToEvent``` function is generic and just expects a hash (or string event name) and a callback.  Now, if there could be a way to instantiate an object to pass to ```subscribeToEvent``` that contained everything, maybe that could be an option.  Just brainstorming, but what about if WidgetEvent was an object that you could instantiate with the callback?  So:
```TypeScript
// exposed duktape class (pseudocode here, 
// but this would be auto-generated as an Atomic JS class *need to figure out how to do that*)
function WidgetEventHandler(callback) { this.callback = callback; }
WidgetEventHandler.prototype.eventName = "WidgetEvent";

// which would be in the d.ts as
export interface WidgetEventHandler {
  constructor( callback: (e:Atomic.UIWidgetEvent) => void) );
  eventName: string;
}

// component code
let handler = new WidgetEventHandler( e=> {
       if (e.type == Atomic.UI_EVENT_TYPE_CLICK) {
           var target = e.target;
           if (target != null) {
               window.text = "Hello: " + target.id;
           }
       } 
    });
window.subscribeToEvent(handler);
```

**Comment by shaddockh** [comment]
One of the problems that I'm running into is that the ```d.ts``` cannot contain any logic.  It's basically just header information that describes the interfaces.  One workaround would be to be able to generate a ```atomicEvents.js``` file that could be automatically ```required``` in during engine startup and then the interface declarations for it stored in the ```d.ts```.  Or else this logic could be migrated into the c++, but I would need assistance for that.  One caveat in having this in c++ is that you wouldn't be able to auto-generate the factory methods for each of the ATOMIC_EVENT types.  When you define a new event, you would need to remember to build a JS factory for it, but if this was in JS, then the JSBind process could auto-generate it.

  Here would be an example of how the ````atomicEvents``` module would look:

```typescript
// The following needs to be generated during build and auto-loaded, or else it needs to be coded directly in C++.
// If generated during build, it could make sense to generate this into a AtomicEvents.js that can be "required" in 
// by the component scripts.
declare type NativeEventCallback<T extends Atomic.NativeEventCallbackData> = (data: T) => void;

// private
function eventFactory<T extends Atomic.NativeEvent>( eventHash: Atomic.NativeEventType, callback: NativeEventCallbackData<T>) : {
    eventHash: Atomic.NativeEventType,
    callback: NativeEventCallback<T>
} {
    return {
        eventHash: eventHash,
        callback: callback
    }
}

// public
function uiWidgetEvent(callback : NativeEventCallback<Atomic.UIWidgetEventCallbackData>) {
    return eventFactory(Atomic.NativeEventType.WidgetEvent, callback);
}

function uiWidgetDeletedEvent(callback: NativeEventCallback<Atomic.UIWidgetDeletedEventCallbackData>) {
    return eventFactory(Atomic.NativeEventType.WidgetDeleted, callback);
}

// .. one for each of the different event types.
```

And then to use it, you would do the following
``` typescript
    let we = uiWidgetEvent(e => {
        if (e.type == Atomic.UI_EVENT_TYPE_CLICK) {
            var target = e.target;
            if (target != null) {
                window.text = `Hello: ${target.id}`;
            }
        }
    });
    window.subscribeToEvent(we);

    // or 
    window.subscribeToEvent(uiWidgetDeletedEvent(e => {
        if (e.widget) {
            // do something
        }
    }));
```

**Comment by JoshEngebretson** [comment]
I am looking into this now and will report
