### ISSUE TITLE
[JavaScript/TypeScript] Add native module enum objects

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#1305]
As a follow up to #1304, the JS and TS API's should have identical enum value resolution.  This requires populating native module enum objects with values that mirror what is currently generated for TypeScript.

On the TypeScript side, ambient declarations for enum values should then be used which reference the JS API enum properties for consistency (including value) 

Important:  The existing JS API enum values should remain intact, though we do need to find a way to deprecate them.

**Comment by shaddockh** [comment]
There's really no way to deprecate them logically other than maybe tacking on a comment that gets emitted in the docs and the intellisense.

It's going to be pretty easy to emit the ambient declarations, but some guidance would be appreciated on how to expose those enums on the native side as namespaced enums instead of constants hanging off of ```atomic```

**Comment by shaddockh** [comment]
I think I figured this out.  Will try to have it done for M3, but may need to push to M4.
