### ISSUE TITLE
2D designer related questions

### ISSUE THREAD

**Issue by gattila** [AtomicGameEngine/AtomicGameEngine#1307]
Hi!

I started to play with Atomic and created a simple 2D test application with typescript. It is just two scene: the first is a simple menu, the second is a blue rectangle with some bouncing balls. It works, but I have some issues and questions.

I created the blue rectangle with the following way: I put four StaticSprite2D (64x64 blue png picture)  and resized/moved to the left, right, top, bottom edge of the designer window. 
![image](https://cloud.githubusercontent.com/assets/7508341/21580939/cad3838e-d019-11e6-8301-5c5e91494216.png)

It looks good, but when I tried to run the code, I have got a following result:

![image](https://cloud.githubusercontent.com/assets/7508341/21580945/0d69dec8-d01a-11e6-9afd-922b86565f01.png)

The another problem, that I don't know how to move the scene vertically and horizontally. I can use Ctrl+Right mouse, or Ctrl+mouse wheel combo, but these are 3D movements and not too useable in 2D design. Is there any way to do this ? I also didn't found how to reset the scene cam roatation/position: I can do it only with editing of the scene.asset.

**Comment by Alan-FGR** [comment]
Hi.

On the first problem, make sure you're not using a perspective projection camera. If that's not the case, perhaps you could send us the project to take a closer look since apparently it's very simple.

Regarding the 2D controls, a proper 2D 'panning' is certainly necessary, what you can do at the moment is while holding the right mouse button use the keys QEAD to pan around, but that's certainly far from ideal. You can use the key 5 to reset to the 'front' view if you mess it up somehow and the O key to toggle perspective/orthographic projection. These however are for the 'editor' camera. If you're talking about the actual runtime camera you have to select it (in the hierarchy) to have access to its attributes in the inspector.

The editor certainly needs a "2D" mode or maybe just a way to pan around in 2D, perhaps using the space key like PS.

Best regards.

**Comment by JoshEngebretson** [comment]
@gattila Hello, please use the Q & A site for questions: https://qa.atomicgameengine.com/

The GitHub issue tracking is for development of Atomic itself.  Thanks!
