### ISSUE TITLE
[Editor] Explore using Blender as scene editor for AtomicEditor

### ISSUE THREAD

**Issue by rosshadden** [AtomicGameEngine/AtomicGameEngine#1343]
This would be sooo cool, it has me giddy just thinking about it.  At the very least, we should support people using Blender as a standalone editor, and not require it.

**Comment by JoshEngebretson** [comment]
This would make an excellent top of discussion on https://discourse.atomicgameengine.com/  

Maybe in the ```Atomic Development``` section, linking to http://armory3d.org/ with some of the images and thoughts which spawned the discussion in chat?

We have 291 issues with this one, gotta herd them a bit ... and if it isn't something that can be attached to a milestone (or staging), probably a discussion needs to happen first :)

**Comment by rosshadden** [comment]
Yeah good points.  My mind is still dwelling in the era before discourse existed I guess!

**Comment by JoshEngebretson** [comment]
No problem, I know things move fast right? 🚀 :)

That armory stuff gives me glee to consider too, if only for ideas due to some pretty major licensing hurdles with GPL3, and I know people will see stuff like this on the community site, only us issue diggers will see it here 💎 

Atomic has an "issue-issue", we've been at it for a couple years, and has been a struggle with project management while bootstrapping the tech...  We're doing much better with the new [Atomic Build milestones](https://github.com/AtomicGameEngine/AtomicGameEngine/milestones), though still have a lot of digging out to do on backlog.  

I'll be making a "staging" milestone for issues, which can be used refine/prioritize the open issues, hopefully closing some out during the sort.
