### ISSUE TITLE
Suggestions and questions about AtomicGameEngine and the asset store

### ISSUE THREAD

**Issue by Raj2032** [AtomicGameEngine/AtomicGameEngine#1668]
I have a few suggestions to improve the AtomicGameEngine which are:

- Have a built in modeling tool
- Have a built in tool that converts anything made in Unity (such as the scripts made in Unity) and convert to something that AtomicGameEngine understands.

I wanted to ask you some questions.

Who regulates AtomicGameEngine assets that are stored in the assets store? Is it Github or is it the owners of AtomicGameEngine ?

Are the users able to upload whatever they want to for the asset store or does it have to go through a mediation/review?

**Comment by mattbenic** [comment]
Hi Raj,
1) A built in modelling tool is way out of Atomic's scope :)
2) There is a script somewhere (I think in one of the other repositories on the AtomicGameEngine account) that converts basic Unity scenes to Atomic ones. It hasn't been touched in ages, and would probably need some maintenance. You're welcome to volunteer for that.
3) There is no Atomic asset store. There are existing assets in the engine, and the samples include some assets. Those are all in the main and sample repositories respectively. Anyone can submit new examples in a PR.

I'm going to close this issue, since it doesn't really specify any actionable tasks. If you have any more questions (as opposed to in-scope feature requests or bug reports) feel free to chat with the community on gitter: https://gitter.im/AtomicGameEngine/AtomicGameEngine

**Comment by Raj2032** [comment]
Hi Mattbenic,

I wanted to know is Atom FOSS - Free (as in freedom) and Open Source Software?

**Comment by Alan-FGR** [comment]
@Raj2032 Atomic is licensed under MIT which is approved by OSI

**Comment by nem0** [comment]
I approve MIT too :nail_care:
