### ISSUE TITLE
Website has invalid SSL Cert

### ISSUE THREAD

**Issue by zauberparacelsus** [AtomicGameEngine/AtomicGameEngine#1698]
When trying to visit https://atomicgameengine.com , chrome blocks me from entering the site because the connection is insecure.  I see the following SSL error when this happens:

`NET::ERR_CERT_COMMON_NAME_INVALID`

**Comment by zauberparacelsus** [comment]
Still getting blocked by chrome :-/

**Comment by baptx** [comment]
It looks like only the URL without HTTPS http://atomicgameengine.com is redirecting to the GitHub repository. By the way, is this fork from Urho3D still maintained? The website is not available since a few months (https://web.archive.org/web/20180516074136/https://atomicgameengine.com/), the last commit was in November 2017 and the Twitter account is not active since July 2017 (https://twitter.com/AtomicGEngine).

**Comment by Alan-FGR** [comment]
@JoshEngebretson hey there, long time no see! :smiley:
@baptx [here's a related thread](https://discourse.atomicgameengine.com/t/status-update-and-passing-the-reins). Most of your code should be compatible with Urho3D except the JavaScript code but it should be easy to port. There are alternative C# bindings for Urho. Godot is a fine option, it has a lot of traction but there are still many things missing. Armory is still not ready for prime time. In my opinion Urho although it's getting dated is still a great game engine.

**Comment by baptx** [comment]
@Alan-FGR thanks for the informations, would it be possible to merge your work on Atomic Game Engine into Urho3D?

**Comment by Alan-FGR** [comment]
Yes, certainly. In terms of API Atomic only changed some names and added stuff on top or Urho. It might require some manual intervention but it's certainly possible. Some new things that were added to Atomic aren't applicable to Urho anymore though, and even the network improvements will be rendered useless when knet is replaced by SLikeNet in Urho.
