### ISSUE TITLE
If JSComponent has a parameter in constructor, it breaks everything

### ISSUE THREAD

**Issue by rsredsq** [AtomicGameEngine/AtomicGameEngine#208]
I found that if JSComponent has a parameter in constructor(any type, any name, it doesn't really matter), then functions like `start`, `update` wouldn't work.
Here's an example of TypeScript code:
```TypeScript
/// <reference path="../Atomic.d.ts" />

class Star extends Atomic.JSComponent {

    constructor(okLetsBreakEverything:any) {
        super();
    }

    start() {
        console.log("ok, start didn't work");
    }

    update(time:number) {
        console.log("update didn't work too :(");
    }

}

export = Star;
```
The same thing with haxe.

**Comment by JoshEngebretson** [comment]
Specifically, this is due to the way that flat JSComponents are detected.  The code uses the function.length to know if it needs to new an instance or call a function with self.  The later being the case for flat function JS components.

I will look into a better detection mechanism, though as JSComponents can be constructed from the scenegraph, any constructor parameter (if supported) will need to be optional with default value

**Comment by JoshEngebretson** [comment]
Closed via https://github.com/AtomicGameEngine/AtomicGameEngine/pull/212

The notes about needing sane default args or checks for undefined as constructors can be called from the scene graph still apply
