### ISSUE TITLE
Inspector not displaying custom component properly

### ISSUE THREAD

**Issue by GarethNN** [AtomicGameEngine/AtomicGameEngine#249]
I created a simple custom component that exposes a single boolean attribute. I register it in a RegisterObject function as follows:

void RenderTexture::RegisterObject(Context* context)
{
context->RegisterFactory<RenderTexture>(GEOMETRY_CATEGORY);
ACCESSOR_ATTRIBUTE("Is Enabled", IsEnabled, SetEnabled, bool, true, AM_DEFAULT);
}

I added it to the "Create Component" button dropdown list, so that I can add this component in-editor via the inspector.

When I use Create Component to add my custom component to a node and save the scene file, I can see if I open the scene file that my component has been added to the node.

But in the inspector isn't displaying it properly.

It shows up first as another Node component on that object, a duplicate of the base Node component with the same parameters.

if I select off the node and then select it again, then the inspector doesn't show my component at all, even incorrectly as a Node component.

But, like I said, in the scene file itself I can see my component attached to the node just fine.

**Comment by JoshEngebretson** [comment]
Hello Garth,

Did you ensure that the class is scriptable?  It must be added to your package JSON in order for AtomicTool to generate the bindings, so it can be accessed via script.  For example: https://github.com/AtomicGameEngine/AtomicGameEngine/tree/3379d404d003441a98df154860b578b5b195a5db/Script/Packages/Atomic

On master, you should be receiving an error message if the ClassID is not available to script:

https://github.com/AtomicGameEngine/AtomicGameEngine/blob/3379d404d003441a98df154860b578b5b195a5db/Source/AtomicJS/Javascript/JSVM.h#L238

What is likely happening, is that the node if ending up on the top of the stack, which is why you are seeing it show up in the component list.  It is possible that a missing class id needs to be a fatal error.

**Comment by JoshEngebretson** [comment]
One note, once added to the JSON, make sure that the AtomicTool project builds (by touching a source file, etc) so that bindings are regenerated.  There isn't a dependency in the solution for the JSON files.

.. or you can invoke it directly and then build:

AtomicTool bind "ABSOLUTE_PATH_TO_ATOMIC_LOCAL_REPOSITORY" "Script/Packages/MyPackage/" "WINDOWS"

**Comment by GarethNN** [comment]
Ah, thanks Josh, that sorted it out. :)
