### ISSUE TITLE
Remember player positioning when run from editor

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#375]
Artist request:
*When playing from the editor, the player opens in the same position, blocking the editor. It should remember the last place it was moved to.

**Comment by JoshEngebretson** [comment]
@rsredsq Instead of saving the position at exit, how about catching E_SCREENMODE and E_WINDOWPOS and forwarding to the editor process to save?

https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Source/Atomic/Graphics/GraphicsEvents.h#L31

I think this will be a lot better and not complicate the process exit
