### ISSUE TITLE
Implement a color picker

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#379]
Artist request:
*Add a color picker for editing colors

**Comment by JustNukeIt** [comment]
In the Editor the color are usually display as 1 1 1 1 (R G B A), it will be nice to replace that box by a Square that is fill with the corresponding color (with the checker pattern to show the alpha). If a level designer click on the square it open a color picker with the different value (like in Photoshop for instance). see ref picture
![colorpickerref](https://cloud.githubusercontent.com/assets/11769017/12555176/8e9a90b8-c388-11e5-82c3-f6e427546065.jpg)

**Comment by JoshEngebretson** [comment]
Thanks, we're planning on implementing a nice color picker with the new UIWebView component landing this week

**Comment by raheelx** [comment]
Hi @JoshEngebretson :) 

did this end up getting landed?

**Comment by JoshEngebretson** [comment]
Yup, the UIWebView component was landed that week.  I misread it this morning as the color picker was landing too, English is hard! :)

There currently isn't a color picker, I'd think there would be a nice web based one somewhere which would be relatively easy to grab and integrate using UIWebView.  Otherwise, maybe we can snag a color picker from somewhere and adapt it, like maybe MIT Torque3D?

**Comment by brandonlamb** [comment]
@JoshEngebretson can this be implemented in TS? Looking through issues to see if there is some non-C++ thing I could attempt to contribute to. Implementing a color picker could be something, and I would greatly desire this feature myself

**Comment by CTrauma** [comment]
is this available from the webview? https://samrueby.com/2014/10/10/did-you-know-chrome-has-its-own-color-picker/

**Comment by shaddockh** [comment]
you would probably want a color picker in the inspector, right?  The web view currently is only used for the code editor.  Would it be possible to launch a small pop up web view from the inspector that exposes a color picker?  Or would that need to be rendered via turbo badger?

**Comment by JimMarlowe** [comment]
There is a package, https://sourceforge.net/projects/tinyfiledialogs/, which is zlib licensed, and it provides a set of cross platform dialogs, one of which is a color picker. It is two files, and can be handled thru the FileUtils class like the nativefiledialogs. After that, adding it to the color inspector would be possible with a "..." button or other means.

**Comment by JoshEngebretson** [comment]
Good find, and a possible replacement for NFD which we've had some problems with at least on OSX and suffers from a lack of updates.  "Best practices" on a file chooser are top level native dialog that the user is accustomed to, not sure about picking up the platform dependency + having top level dialog for the color chooser, brought up and torn down per color choice.

I don't think this would be a great use of the WebView, though it would probably be pretty easy to hook one up in that manner.  In this case, I would definitely cache the UIWebView widget and reuse it instead of firing up a new instance per color pick which would be heavy handed.

We do need one... was thinking it might be possible to borrow some code from imgui or possibly Torque3D's color picker and factored into a TB widget (natively).  There is a hsv color wheel in AngelScript in Urho3D's editor for reference as well: https://github.com/urho3d/Urho3D/blob/a794f9e59b0e707960ca7b26d99d12b182ae1989/bin/Data/Scripts/Editor/EditorColorWheel.as

**Comment by JimMarlowe** [comment]
The TinyFileDialogs color picker is admittedly not a perfect solution, but would be a step up from the current interface without much R&D. Editing a color is currently difficult. I can do some guesses for simple colors with floating point RGB ratios, but the increment arrows for the values step by 1.0, this means 3 hand edits to select any color. 
Also, I tried the version 2.5.5 of tinyfiledialogs, and the hello.c demo program has problems, but the 2 library files are fine.

**Comment by JoshEngebretson** [comment]
A major factor in developing Atomic is cross platform support and the maintenance that results.  Any introduction of platform dependent code needs to be carefully considered, especially if it is an interim solution.  

Did you test on Windows, OSX, and Linux?  Platform dependencies like this can have some surprising side effects, for example on OSX the platform file chooser uses GL for compositing which can interfere with our SDL GL context.   I am able to handle Windows, OSX, and on Linux keep the AtomicPlayer running and the AtomicEditor at least starting up and loading projects.

I  would really like to avoid popping up a top level dialog right now for this, and it sounds like you might have some ideas how the editing can be improved in the inspector itself, for example the increment, or perhaps being able to paste a color hex value into the inspector?

**Comment by JimMarlowe** [comment]
A dialog box with a TB interface file, and implemented in TS is fair game then? Are the Color object's HSL conversion functions exposed to JS?

**Comment by JoshEngebretson** [comment]
Only descendants of RefCounted are auto-bound for performance reasons.  Color's are handled as simple arrays in JS, it would probably be best to implement the specific color conversion functions in TS/JS rather than marshal to native code to run the math functions there in this case.

Yes, a TB window would be great, I think some ideas on implementation from the Urho color wheel could work (https://github.com/urho3d/Urho3D/blob/a794f9e59b0e707960ca7b26d99d12b182ae1989/bin/Data/Scripts/Editor/EditorColorWheel.as), for example here's the HSV texture: https://github.com/urho3d/Urho3D/blob/a794f9e59b0e707960ca7b26d99d12b182ae1989/bin/Data/Textures/Editor/HSV20.png

It would be a good idea to run the Urho editor and use the color wheel a bit to see if the implementation seems solid.

**Comment by JimMarlowe** [comment]
I need a detailed idea for what an artist would need in a color picker. What is important for them, and I guess other people too? The available pieces are now :  UIColorWheel (HS) And a Slider (L) the centerpiece,  UIColorWidget displays color+alpha,  UIInlineSelects,  UISliders,  UITextFields.  A ransom note or mockup picture of the arrangement would be ok.

**Comment by JoshEngebretson** [comment]
Color Picker now on master:

**VIDEO:** https://www.youtube.com/watch?v=2J7enXe8wFY

There are followups for avoiding having multiple pickers active, closing picker when selection changes, or at least invalidating it, etc.  Though, big usability level up :)
