### ISSUE TITLE
.asset file line endings differ across platforms

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#452]
Opening one of the example projects on Windows, and then checking for differences in git, the line endings of .asset files  (which I assume were created on OSX) have changed. We've also seen this happen between different windows machines on our own assets, oddly enough. 

Serializing assets should use a single line ending format across platforms.

**Comment by Type1J** [comment]
MSYS Git on Windows should modify the line endings on checkout and commit. Is Git how you're moving the files between machines, or are you using a network shared volume?

**Comment by mattbenic** [comment]
Oddly enough we're not even working across different platforms. We're seeing that opening a project (on Windows) already committed to git (also on Windows) results in the asset files being modified, purely line ending changes.

**Comment by Type1J** [comment]
I still think that this is probably a git issue. Try this: On every Windows machine, do the following:

    git config --global core.autocrlf true

This will cause Windows line endings for everybody, but it will check-in Unix line endings. If you want Unix line endings everywhere, then do this on all of the machines:

    git config --global core.autocrlf false

Most Windows editors will mess up your files with this option, so I'd recommend setting it to "true". However, to which value it's set is less important than it being set to the same value across all of your machines.

You'll need to checkout the files again after these commands. You might want to just clone the repo again, since that's the easiest thing to do.

**Comment by Type1J** [comment]
By the way, I'm assuming that you're using MSYS Git. If you're using another version of Git, this might not work.

**Comment by mattbenic** [comment]
I thought it a git issue as well, and actually thought I'd sorted it out but I see our artists still having issues. 

Yeah we are using MSYS, I'll give it a shot, thanks and close this if it helps.

**Comment by Type1J** [comment]
I'm sorry if you felt pressured to close the issue. Don't worry, nobody benefits from that. The only agenda I have commenting on this issue is to help you.

Please let us know here how you end up resolving this issue.

I think that there's a 'core.eol' option for git that you might want to look at as well.

**Comment by mattbenic** [comment]
Sure I get that and appreciate it :) Just haven't had a chance yet.

**Comment by mattbenic** [comment]
This did turn out to be a git issue. Though for reference in case anyone else is looking the solution was to have git treat .asset use unix endings. Rather than doing this globally, we added:

*.asset text eol=lf

to our .gitattributes in just our atomic git repo.
