### ISSUE TITLE
New code editor: several Edit menu options are not working (see note)

### ISSUE THREAD

**Issue by LaraEngebretson** [AtomicGameEngine/AtomicGameEngine#697]
The following Edit menu options do not work on Windows/OSX:
cut, copy, paste, select all, undo, redo

Note: the hotkeys work

**Comment by JoshEngebretson** [comment]
This is no longer an issue

**Comment by shaddockh** [comment]
I'll take this one.  I think it's a matter of forwarding that message to the web view from the menu click and then responding to it in the javascript in the web view.  There may be an issue with allowing the CEF window to access the system clipboard for cut/copy/paste commands from javascript.

**Comment by shaddockh** [comment]
@JoshEngebretson 
I've started implementing this by calling the ```webClient->ShortcutUndo, ShortcutPaste```, etc.  However I don't this this will work.  The following issues have cropped up:

1. The web client is not in focus when the menu is pressed, so paste is not working correctly.  I think that sending the ```SendFocusEvent``` may be happing async, so there needs to be some kind of callback for when the webview is actually in focus.  This is showing itself when firing the ```Paste``` event and the monaco editor is actually throwing an error claiming that the paste event could not be performed because the editor was not in focus.

2. It appears that the web view commands for ```Paste, Undo, Redo```, etc. are not getting picked up correctly by the Monaco editor.  For instance, calling the ```Undo``` function on the webclient will only periodically execute an undo, and the undo does not seem to behave correctly.  But when pressing CTRL/CMD-Z inside the editor, it performs logical undo steps and ensures that the cursor is moved appropriately and entire words are removed (instead of just a character at a time).  Unfortunately, the monaco editor does not expose an API for calling undo directly or else I would just hook into that.

I'm thinking that maybe calling ```void WebClient::SendKeyEvent(const StringHash eventType, VariantMap& eventData)
``` with the actual key codes would correctly fire the event inside the Monaco editor.  Is there an example of how to do this from the C++ side?  I'm not sure what to populate in the method signature.

**Comment by JoshEngebretson** [comment]
Something like this? https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Source/AtomicWebView/WebKeyboardMac.cpp#L67

Note that there are also Windows and Linux versions of that file, the mapping logic might be a candidate for some refactoring/combining

**Comment by shaddockh** [comment]
I think I got it.  I'm forcing the CTRL/CMD+Z and CTRL/CMD+SHIFT+Z through the SendKeyEvent so that it behaves properly.  Also, I found that CEF has an option to allow javascript_dom_paste and by enabling that, it is possible to handle the paste event from within the editor javascript code.
