### ISSUE TITLE
Add method to easily take screenshots from the Atomic Editor

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#715]
This might be a key combo, or possibly a menu item that has a short delay (to not capture UI), also we need a preference dialog to save where screenshots are stored

**Comment by JimMarlowe** [comment]
I've found the Atomic.graphics.takeScreenShot(myimage) works acceptably for taking a screenshot of the editor (bonus, cross-platform), if that's what want. Note, it will not capture the window frame, since that is provided by the OS.
For storing the screenshots, the minimum that is needed is (until there is a preferences dialog...) :
  a screenshot path (default =s ame as for projects),  in preferences
  a save format (png, jpg, bmp, tga, dds),  in preferences
  an autogenerated filename, Screenshot_dd_mm_yyy_HH_MM_SS.ext
  a menu entry in Developer->Screenshot
  a key combo, Ctrl+9?

**Comment by JimMarlowe** [comment]
closed with #1450
