### ISSUE TITLE
Line number reporting in javascript component errors is incorrect

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#72]
This occurs in any script with more than a few lines of code, the following component will recreate it (the error will be reported at line 12, instead of line 9):

// Atomic Component

var game = Atomic.game;
var ui = game.ui;
var root = ui.getRoot;

var uiStyle = game.cache.getResource("XMLFile", "UI/DefaultStyle.xml");
foo
function start() {
    
}

function update(timeStep) {

}

**Comment by JoshEngebretson** [comment]
This is due to some JS bookkeeping happening: 

https://github.com/AtomicGameEngine/AtomicGameEngine/blob/script_widget/Source/AtomicJS/Javascript/JSVM.cpp#L157

So, the error event needs to know the error is coming from a JS component script and then adjust the line number.  Other scripts should be unaffected.

**Comment by JoshEngebretson** [comment]
This should no longer be an issue as the component wrapper magic is gone
