### ISSUE TITLE
Event constants should be generated in ts by JSBind

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#726]
Event string constants are scattered all over the place in ts, sometimes used directly in subscribeToEvent calls. Events generated by native code should be output to Atomic.d.ts for better reference and consistency.

**Comment by shaddockh** [comment]
+1 I'm running into this as well when trying to share events between the TS and native code.  Ideally, if possible, both event names and structures should be defined in the native code and emitted as the following in the d.ts:

``` typescript
declare module Atomic.EditorEvents {
     export var CustomEventName;

     export interface CustomEvent {
       path: string;
       othervalue: string;
    }
}
```

You can't store constant strings in the d.ts, but if they reference a native constant, it should work.

**Comment by JoshEngebretson** [comment]
Yeah, this would be great.  There are a couple issues here native side, 1)  Events are defined in preprocessor macros and 2)  They don't have type information (any type information is generally a comment string)

I have to look into whether we're getting preprocessor symbols in the header traversal (dubious on this) and then can look into adding type info to the existing events.  Failing this we could make a concentrated effort to do existing events by hand, there's not a ton, and then keep them updated in the relatively rare event of a new native event that is also accessible by script.  These kind of processes aren't too bad, especially if they are documented.

**Comment by shaddockh** [comment]
Based upon some work I was doing last night, the number of native events may increase.  In order to pass an event from the Typescript editor code to the CEF code (such as a file rename event), it needs to be routed through the native code.   The native code needs to be able to subscribe to the TS generated event and then turn around and call the appropriate exposed javascript function in the CEF instance.

**Comment by JoshEngebretson** [comment]
There are a few ways to communicate with the page in both directions, I need to add some examples to make them more clear.  I think we can probably shorten the trip and maybe avoid needing to define events for fine grained communication.  The other thing is that event definitions are really just string hashes, so they don't really need to be "defined", unless native code is responding to a specific event.

**Comment by mattbenic** [comment]
And here I thought this was just an OCD request on my part, glad it's turning out to be others are keen on as well :)

**Comment by mattbenic** [comment]
Just pinging on this, it's an issue in C# as well. The constants solution for exposing all consts works well, exposing the events in a similar way would be awesome.

**Comment by JoshEngebretson** [comment]
There's are a ton of native events and the definitions are in preprocessor blocks which lack type informations:

```
/// Node's physics collision ongoing. Sent by scene nodes participating in a collision.
ATOMIC_EVENT(E_NODECOLLISION, NodeCollision)
{
    ATOMIC_PARAM(P_BODY, Body);                    // RigidBody pointer
    ATOMIC_PARAM(P_OTHERNODE, OtherNode);          // Node pointer
    ATOMIC_PARAM(P_OTHERBODY, OtherBody);          // RigidBody pointer
    ATOMIC_PARAM(P_TRIGGER, Trigger);              // bool
    ATOMIC_PARAM(P_CONTACTS, Contacts);            // Buffer containing position (Vector3), normal (Vector3), distance (float), impulse (float) for each contact
}
```

Some of which, like in the P_CONTACTS case above need to be converted to be usable by script handlers.  I don't think the C++ parser handles preprocessor stuff, though a simple regex could pick up  the "E_MYEVENT" and "MyEvent" for autogeneration, this would only be for the event id however.

It would probably be better to wrap the events up with typesafe Event subclasses, so you would have something like what I did for this physics collision (which is "worst case" in the VectorBuffer usage of P_CONTACTS): https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Source/Atomic/Script/ScriptPhysics.h#L45

If we did this, we could hook them up in C# using specific delegates, instead of the general event handler one which has to query from a ScriptVariantMap without type information (which is absent in the C++ declarations)

**Comment by JoshEngebretson** [comment]
In the near term, adding string constants like:

```
const string E_NODECOLLISION = "NodeCollision";
```

Would formalize the ID handling part, which is a confusing bit when setting up handlers.  It definitely feels wrong to use "NodeCollision" and E_NODECOLLISION feels more correct :)

**Comment by mattbenic** [comment]
Perhaps as an interim they should be collected as consts in AtomicWork.ts, that would at least provide a single place for people to look

**Comment by JoshEngebretson** [comment]
C# now has typesafe events, these should be pretty easy to add to TS bindings now too

**Comment by shaddockh** [comment]
TS has typesafe events now too.  This should be able to be closed.
