### ISSUE TITLE
[NEW FEATURE] SWIG for interop?

### ISSUE THREAD

**Issue by brandonlamb** [AtomicGameEngine/AtomicGameEngine#867]
Just putting this here for visibility.

Came across SWIG which seems to promise autogeneration of headers, etc and binding for potential for C# *and* Java?

Would be cool to be able to use groovy on JVM or C#.

I tried to dive into it but without more direction I dont quite have the skillset.

**Comment by JoshEngebretson** [comment]
SWIG has been around the block a few times and I have done a fair amount of stuff with it.  It is a pretty big dependency and requires interface files which can be difficult to sync with sources.  Also, it doesn't currently have a Duktape binding target as far as I know.  

AtomicTool includes a C++ parser which is capable of parsing the engine source code and currently has Duktape binding and a good start on C# bindings, which are engine specific.  Swig is able to generate an XML representation of C++ headers, which is cool (though this can be difficult to parse in itself).

In my experience, binding with a generic tool gets you somewhere pretty fast, though the devil is always in the corner cases and integration.  What might be cool for Atomic is a Swig interface generator, so emit a Swig interface instead of bindings, which can then be used to generate various bindings.  

We need better native C++, JS/TS, and C# support before can really look into other languages, and I would venture that languages which target JS (CoffeeScript for example), and Haxe which targets other languages and for [which there is already a MIT Atomic project](https://github.com/rsredsq/atomic-haxe), in addition to languages that run on the CLR would be good fits as we get these for "free", aka no additional native bindings.
