### ISSUE TITLE
[Linux] Build failes

### ISSUE THREAD

**Issue by RameshRavone** [AtomicGameEngine/AtomicGameEngine#888]
-- curl version=[7.40.0]
-- Enabled features: SSL IPv6 unix-sockets libz NTLM
-- Enabled protocols: HTTP HTTPS
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ravone/Works/AtomicGameEngine
jake aborted.
Error: make: *** No rule to make target 'GenerateScriptBindings'.  Stop.
    at api.fail (/home/ravone/Works/AtomicGameEngine/Build/node_modules/jake/lib/api.js:336:18)
    at null.<anonymous> (/home/ravone/Works/AtomicGameEngine/Build/node_modules/jake/lib/utils/index.js:124:9)
(See full trace by running task with --trace)

**Comment by JoshEngebretson** [comment]
Are you using "./Build_AtomicEditor.sh"?  What distro/version of Linux are you using?

**Comment by RameshRavone** [comment]
I am using Ubuntu 16.04.

./Build_AtomicEditor.sh is what causes the problem. but QTCreator finishes the job and now its
"ERROR: Failed to add resource path 'CoreData', check the documentation on how to set the 'resource prefix path'"

**Comment by JoshEngebretson** [comment]
This is due to building a redistributable build with ./Build_AtomicEditor.sh which is interrupted, and then "finishing" the build with QtCreator/make which does not package the editor resources.  Instead of doing this... make a directory alongside the local AtomicGameEngine repository like "AtomicGameEngine-Build", cd into it and:

```cmake -DCMAKE_BUILD_TYPE=Debug ../AtomicGameEngine && make -j4``` which will build a development binary in the AtromicGameEngine-Build Source folder, otherwise please see: https://qa.atomicgameengine.com/28/how-to-build-from-source-in-debug

I'll double check the Linux release build script, however looking in the CMake files the GenerateScriptBindings is present.

**Comment by JoshEngebretson** [comment]
Builds on Ubuntu 14.04 with ./Build_AtomicEditor.sh without issue, and here is the GenerateScriptBindings target: https://github.com/AtomicGameEngine/AtomicGameEngine/blob/c9f0328fd9d60c873ebf78e6d62a5219b1cdd611/Source/AtomicTool/CMakeLists.txt#L43

If you are still having issues, please post exactly how you are building, also ensure you have cloned the repository recursively: git clone --recursive https://github.com/AtomicGameEngine/AtomicGameEngine

**Comment by RameshRavone** [comment]
I don't know what happened but my re-clone just fixed it. Anyway thanks man and keep your best, Really looking forward to working with you all.
