### ISSUE TITLE
[Linux] Pulse audio issues with CPU usage and black screen at startup

### ISSUE THREAD

**Issue by jeremyjh** [AtomicGameEngine/AtomicGameEngine#940]
I followed the build instructions and built the latest master on Ubuntu 14.04 64-bit. After launching the editor I can see it continuously uses 110-120% CPU as reported in top. This is before opening a project, as well as with a project open. Games seem to run fine, its just an issue with the editor.

**Comment by JimMarlowe** [comment]
If top shows SDLAudioDev2 as the process using most of the cpu, it can be changed by adding the environment variable "export SDL_AUDIODRIVER=pulseaudio". 
Note, this will make the game preview from the editor not have sound. 
The SDL 2.0.4 that came in Aug 8, is suppose to have fixed this SDL issue.

**Comment by jeremyjh** [comment]
Top shows AtomicEditor using the CPU. Also, my earlier statement was incorrect - it is an issue playing games as well, the physics platformer burns two cores.

**Comment by JoshEngebretson** [comment]
By default the AtomicPlayer runs with an uncapped framerate, there is a maxFps property on the Engine subsystem which should limit it: 

http://docs.atomicgameengine.com/api/classes/atomic.engine.html#maxfps

In main.js, Atomic.engine.maxFps = 60; // should limit CPU usage

The editor does this, not sure what is going on there:

https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Script/AtomicEditor/editor/Editor.ts#L46

**Comment by jeremyjh** [comment]
Why does it use *two* cores though while playing a game, even if launched from `AtomicTool play`? Is it still drawing the editor  at 60 fps in a hidden window?

**Comment by JoshEngebretson** [comment]
I am not sure profiling should help figure it out, on OSX pressing play from the editor, the editor and player processes are using expected amounts of CPU at 60 fps cap:

![screen shot 2016-08-10 at 9 00 15 pm](https://cloud.githubusercontent.com/assets/376203/17578446/7f6ebdac-5f3d-11e6-98fc-1dea34119250.png)

**Comment by JoshEngebretson** [comment]
BTW, AtomicTool play just launches an editor instance in player mode, which doesn't have any editor stuff running.  The engine is threaded and does use work queues, also could be a SDL thread, where there have been issues with CPU usage and audio as @JimMarlowe mentioned.

**Comment by EternalXY** [comment]
I've seen high CPU usage on Linux as well, in my case it was because of the ALSA sound thread.
Capping frame rate & applying these changes brought down the CPU usage to normal levels:

Uncomment this in SDL_alsa_audio.c
/* ALSA_snd_pcm_wait(this->hidden->pcm_handle, -1); */

and remove this function call:
 /* Switch to blocking mode for playback */
ALSA_snd_pcm_nonblock(pcm_handle, 0);

**Comment by jeremyjh** [comment]
Using the pulseaudio idle brought idle down to 30% in editor with no
project open. Still high but a lot better. It cuts usage in half for the
game but didn't have a chance to try capping FPS yet.

**Comment by JimMarlowe** [comment]
I check the editor's cpu usage with the newer SDL 2.0.4, and it was still over 100%, so the hopeful fix from the new SDL did not materialize.

**Comment by JoshEngebretson** [comment]
Perhaps SDL 2.0.5 addresses this, @JimMarlowe would you mind building Urho master (which is on 2.0.5 now) and seeing if this is the case with audio?

**Comment by JoshEngebretson** [comment]
pulseaudio can block editor startup (black screen) so adding this to current build with high priority

**Comment by JimMarlowe** [comment]
I tried the latest Urho3D with SDL 2.0.5, and observed that the Urho3D editor behaved the same as with SDL 2.0.4, also noting that it does not rocket to 100%+ cpu usage, like many products do that are using SDL/pulseaudio in the same way we do.

**Comment by JimMarlowe** [comment]
This is what I now know. SDL_Audio on linux is good, unless you have a problem, then it's bad.
    PulseAudio, I found, is not the problem that is causing the high cpu usage. In fact, the PulseAudio driver can not even be initialized in SDL even if you wanted to, the api loader errors out, and even if you could load the driver, the next step that connects it to a puleaudio server, which segfaults. No one is using SDL and pulseadudio on linux, they can't. We'll move on.
   @EternalXY had it right (thanks), it is the ALSA SDL implementation that is coded poorly. SDL had half the solution in a comment! (now in their latest 2.0.6?) and the other half they are now aware of apparently. I don't know which distro they test on, but a large number of SDL based programs, have this issue, like steam.
    The effect of setting "export SDL_AUDIODRIVER=anything" means the SDL_Audio skips the driver discovery phase of initialization and ONLY initializes what the environment variable is set to. If you set it to a driver that you can not initialize, then you get NO AUDIO in your program. For the AtomicEditor, that's probably OK, since it doesn't currently play any sounds. But if you play from the editor, the player that is invoked is an AtomicEditor in disguise, and that also will not have any sound. 
For @spacepluk's problem with the black screen, this is a driver issue probably related to Arch having a leading edge ALSA driver, instead of the version that ubuntu uses. The crash is coming from inside /usr/lib/libasound.so.2, which is some place that Atomic can not control, or even detect the problem. The solution here may be to put it in the FAQ and note the solution and side effects.

**Comment by JoshEngebretson** [comment]
Conquered in #1384, thanks @JimMarlowe!

![conan](https://cloud.githubusercontent.com/assets/376203/21995754/75b3a83e-dbdb-11e6-8468-5c8cd6ccb095.gif)
